### PR TITLE
Script and schema for CAMELS FoF Catalog

### PR DESCRIPTION
**Pull request by lmachadopolettivalle**
In preparation for the CAMELS data release, we are adding a schema and an ingestion script for the `CAMELS FoF Halo` dataset.

Schema:
- Includes all available fields for the FoF Halos in CAMELS, both for IllustrisTNG and SIMBA.

Script:
- Loops through all directories with CAMELS datafiles, and inserts data from all available files into Elastic Search.
- The script uses `illustris_python` to read the CAMELS data. The code can be cloned from the `illustris_python` repo, and requires a minor change to be used properly here.

### CODE REVIEW

**Comment by dylex** [comment]
This all looks reasonable, thanks.  Do you have thoughts about the subhalo catalogs?  We had planned to move to an integrated (joined) catalog containing both for illustris/tng, or we can start with just the fof for the initial release.

**Comment by lmachadopolettivalle** [comment]
I can write a similar script and schema for the CAMELS Subhalo catalog and push it here. I did not find a simple way to join both catalogs, so I think we can start with the separate catalogs (as they currently exist for e.g. TNG) and later combine them as you suggested. How does that sound?

**Comment by dylex** [comment]
I guess it just depends what we want in the initial release.  I thought Shy had suggested we release the combined catalog, but we can do only the fof or separately too.  It probably makes sense to at least at the subhalo catalog schema so we have it, and can decide from there.

**Comment by lmachadopolettivalle** [comment]
I have added the Subhalo catalog schema, and changed the Python script to ingest Subhalo data as well. Now FlatHub should be ready to ingest all CAMELS catalog data!

**Pull request merged**
